feat: context saving for side navbar
OneBusAway/onebusaway-docs pull request #63
Opened 2024-03-11 18:59 UTC by ankitkumar748846

#### Description:  The sidebar scroll is not functioning properly, leading to a poor user experience.

#### Issue fixed: #62 

#### Changes done:
- [x] Task 1

#### Screenshots/Videos

Before:

https://github.com/OneBusAway/onebusaway-docs/assets/109648585/af95b57e-a990-4426-aad3-d0edc6594235

After:

https://github.com/OneBusAway/onebusaway-docs/assets/109648585/b8afe701-ce82-4aed-9692-db9597e3e947

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Tried squashing the commits into one

2024-03-11 21:08 UTC, aaronbrethorst requested changes
This is a great improvement to the site's behavior! Couple things to fix before it can be merged, though.

2024-03-11 21:08 UTC, aaronbrethorst commented on src/_layouts/default.erb
> +          <div id="context-save" class="contents lg:pointer-events-auto lg:block lg:w-72 lg:overflow-y-auto lg:border-r lg:border-zinc-900/10 xl:w-80 lg:dark:border-white/10">
please rename the id to something that provides context on what the element is, like `id="navigation-sidebar"`

2024-03-11 21:08 UTC, aaronbrethorst commented on frontend/javascript/index.js
> +function contextSave() {
please rename this to something that provides more context on what it's doing (no pun intended). I would recommend naming it something like `saveAndRestoreNavigationPosition`

2024-03-11 21:08 UTC, aaronbrethorst commented on frontend/javascript/index.js
> +  var scrollPosition = localStorage.getItem('scrollPosition');
this should be stored in `sessionStorage` instead of `localStorage` so that it isn't preserved across multiple site visits.

2024-03-11 22:05 UTC, ankitkumar748846 commented
@aaronbrethorst Okay sir

2024-03-15 05:12 UTC, aaronbrethorst commented
implemented in #72

2024-03-15 05:12 UTC, closed without merging