Added the feature of copying the headings using link icon
OneBusAway/onebusaway-docs pull request #70
Opened 2024-03-12 06:56 UTC by tarunsinghofficial

#### Description:

Added a feature for enhancing the user experience by providing a seamless way to copy direct links to specific headings within the content using a link icon next to headings. Features implemented:

- Improved Copy Functionality
- Smooth Scrolling
- Visibility Toggle

#### Issue fixed:

Fixed #69 

#### Changes done:
- [x] Task 1

#### Screenshots/Videos
![bandicam2024-03-1212-18-59-504-ezgif com-crop](https://github.com/OneBusAway/onebusaway-docs/assets/62840625/b395c9a9-9150-4731-b77c-5ceb541179e1)

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Tried squashing the commits into one

2024-03-12 15:24 UTC, aaronbrethorst requested changes
This is cool, thanks for adding it! I see a few things that will need to be addressed before merging.

1. The link icons are invisible in light mode.
2. the `<svg>` elements you're generating all have the id `link`. An id is supposed to be unique on the page.

![2024-03-12 08 22 39](https://github.com/OneBusAway/onebusaway-docs/assets/2254/13266003-025d-43e1-a1eb-502f9fa26f20)

2024-03-12 15:49 UTC, aaronbrethorst commented
make sure you've pulled the latest bits from main and rebased on top of them. #74 will affect this PR.

2024-03-12 15:51 UTC, tarunsinghofficial commented
Okay! Got it. I am working on this.

2024-03-13 14:22 UTC, closed without merging

2024-03-13 14:25 UTC, tarunsinghofficial commented
**I am working** on this PR again as I have some issues in my local storage.

2024-03-16 13:07 UTC, tarunsinghofficial commented
HI @aaronbrethorst, a new PR #90 has been created in place of the given PR. Please check it! Thanks.