Fixed all 7 internal permalinks
OneBusAway/onebusaway-docs pull request #84
Opened 2024-03-13 21:35 UTC by gorgwu

#### Description:

Fixed all 7 internal permalinks in arrival-and-departure-for-stop method.

#### Issue fixed:

#### Changes done:
- [x] Corrected file paths so internal permalinks link to the intended page

#### Screenshots/Videos

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Tried squashing the commits into one

2024-03-13 21:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OneBusAway/onebusaway-docs?pullRequest=84) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OneBusAway/onebusaway-docs?pullRequest=84) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OneBusAway/onebusaway-docs?pullRequest=84) it.</sub>

2024-03-14 18:47 UTC, aaronbrethorst requested changes
these permalinks don't appear to be broken. Were you testing this out with the Bridgetown server running locally, or just looking at the linking structure between individual markdown docs?

2024-03-14 21:03 UTC, closed without merging

2024-03-14 22:13 UTC, gorgwu commented
Yeah, whoops - I got a bit ahead of myself. I set up Bridgetown and then began running the markdown in my IDE without actually testing it in Bridgetown. Sorry about the inconvenience, definitely not making that mistake again.

2024-03-14 23:05 UTC, aaronbrethorst commented
no worries :)