Fixed :Adjusted padding to prevent Copy button overlap with code block
OneBusAway/onebusaway-docs pull request #96
Opened 2024-03-17 17:01 UTC by Devmoni

#### Description:

Fixed  #94 

#### Issue fixed:

Added padding to prevent Copy button overlap with code block.

#### Changes done:
- [x] Task 1

#### Screenshots/Videos

![Screenshot from 2024-03-17 22-26-26](https://github.com/OneBusAway/onebusaway-docs/assets/121149738/cca9c9e8-4dc3-4181-802a-9e1c57c289f9)

![Screenshot from 2024-03-17 22-25-44](https://github.com/OneBusAway/onebusaway-docs/assets/121149738/f5e6e0ab-f04f-4967-9dc6-f20aa79a23e5)

#### ✅️ By submitting this PR, I have verified the following

- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Tried squashing the commits into one

2024-03-18 04:18 UTC, aaronbrethorst requested changes
Thanks for taking a stab at this. I don't love having a large empty space at the beginning of every code block. You can see that GitHub is actually afflicted by the same issue.

<img width="768" alt="image" src="https://github.com/OneBusAway/onebusaway-docs/assets/2254/d6c5a652-785e-4f9d-b77f-2ea74faa5e5e">

2024-03-18 04:31 UTC, Devmoni commented
Thank you @aaronbrethorst sir for your feedback. 

I have a suggestion: How would it be if we added a surrounding around the copy button, similar to GitHub's? This could help in identifying the copy button more easily, especially in longer codes.

2024-03-18 14:53 UTC, aaronbrethorst commented
@Devmoni I think a border would be a good improvement.

2024-03-18 15:16 UTC, Devmoni commented
Ok sir I will do the same.

2024-03-19 17:29 UTC, aaronbrethorst approved these changes
👍

2024-03-19 17:30 UTC, merged